org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.19.2
forge_version=43.5.1
mapping_channel=official
mapping_version=1.19.2

mod_id=darkness
mod_name=Darkness Client
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.darkness
mod_authors=ScriptCreator109
mod_description=Cheat client para Forge 1.19.2
